# Generated by Django 3.2.8 on 2021-11-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_auto_20211109_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='state',
        ),
    ]
